class Exercise {
  String title;
  String subtitle;

  Exercise({
    this.title = 'Workout Senin',
    this.subtitle =
        '20 menit • Jumping Jack, Plank, Walkouts, Reverse Crunches, Russian Twists, Push Ups',
  });
}

var workouts = [
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
  Exercise(),
];
